---
ID: "91300a2e-6159-4cd4-9a29-3cfe969ed40a"
Parent: "d8f6e045-b2e7-45d5-9858-fd7109117913"
Template: "d8f6e045-b2e7-45d5-9858-fd7109117913"
Path: /sitecore/templates/Project/Workshop/Page Types/Doctor/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{F87B150E-D0B0-4F9D-BE86-473A57D07E23}">
        <r
          ds="{FEB45060-A9C5-4BE5-BF2F-2B423DC8FC90}"
          id="{DA90AEF9-E5A1-4E56-8C98-2BD96997C6DD}"
          par=""
          ph="header"
          uid="{98EC0F08-34D1-4DE5-BB04-DC4A6446F31B}"
          ccb="Clear on publish" />
        <r
          id="{59034D87-DC57-44AE-B188-8F5987ABED08}"
          ph="navigation"
          uid="{CB7C63A0-C866-433D-BA8A-EBC36C468D1D}" />
        <r
          id="{15767219-BB3F-43FE-9419-45D33CDB41C3}"
          ph="main"
          uid="{C1903890-19F6-4A6B-8358-C05AA27C0F5B}" />
        <r
          ds=""
          id="{A9E66817-27A8-459D-ABCE-D7B59BEA089E}"
          par=""
          ph="/main/col-1"
          uid="{CECA7F67-D816-49FA-96CD-DFB6F8F3FDE8}"
          ccb="Clear on publish" />
        <r
          ds="{35ECC186-62E7-4BE1-8023-7DC6892A8724}"
          id="{01ADFBCE-7C10-455C-BD30-5CA066074169}"
          par=""
          ph="footer"
          uid="{07DC0804-BE6B-4F1D-A67A-050E00259277}"
          ccb="Clear on publish" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240113T022858Z
    - ID: "2aa86b7b-4f30-41dc-b7d3-405ee4303ea8"
      Hint: Title
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "91bf8efe-4fe5-47f7-adde-b970078f7d51"
      Hint: Name
      Value: $name
