---
ID: "a9875030-fd27-4fcc-87bf-6652e930eaf9"
Parent: "d9173dda-0a4d-4dcb-88bd-d2ba88dd3981"
Template: "d9173dda-0a4d-4dcb-88bd-d2ba88dd3981"
Path: /sitecore/templates/Foundation/Datasources/Page Datasource/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240101T220307Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
