---
ID: "d593a727-fa86-4b89-8be5-754c049e0f2d"
Parent: "13d7a518-27e5-4b48-bef5-6ea410ed4702"
Template: "13d7a518-27e5-4b48-bef5-6ea410ed4702"
Path: /sitecore/templates/Foundation/Datasources/Component Datasource/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240101T220451Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
